# Generated by Django 3.2.6 on 2021-08-25 17:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AArtCategoryArtCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'a_art_category_art_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AArtTourTour',
            fields=[
                ('id_Point_of_interest_Tour', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.DecimalField(decimal_places=0, max_digits=15)),
            ],
            options={
                'db_table': 'a_art_tour_tour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AEventCategoryEventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'a_event_category_event_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('classid', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('descr_it', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=200, null=True)),
                ('name_it', models.CharField(max_length=100)),
                ('area_di_download', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('notes', models.CharField(blank=True, max_length=1024, null=True)),
                ('open_time', models.CharField(blank=True, max_length=1024, null=True)),
                ('tickets', models.CharField(blank=True, max_length=1024, null=True)),
                ('rss', models.CharField(blank=True, max_length=30, null=True)),
                ('saving_vc', models.FloatField()),
                ('vc', models.CharField(max_length=80)),
                ('vc_id', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'art',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArtCategory',
            fields=[
                ('classid', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('name_it', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'art_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArtCategoryNameTradT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_trad_value', models.CharField(max_length=16384)),
            ],
            options={
                'db_table': 'art_category_name_trad_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArtDescrTradT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr_trad_value', models.TextField()),
            ],
            options={
                'db_table': 'art_descr_trad_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArtNameTradT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_trad_value', models.CharField(max_length=16384)),
            ],
            options={
                'db_table': 'art_name_trad_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArtTradT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(blank=True, max_length=80, null=True)),
                ('notes_trad', models.CharField(blank=True, max_length=16384, null=True)),
                ('open_time_trad', models.CharField(blank=True, max_length=16384, null=True)),
                ('tickets_trad', models.CharField(blank=True, max_length=16384, null=True)),
            ],
            options={
                'db_table': 'art_trad_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BenefitVc',
            fields=[
                ('classid', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('benefit', models.CharField(max_length=1024)),
                ('descr', models.CharField(max_length=2048)),
                ('title', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'benefit_vc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BenefitVcBenefitTradT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_trad_value', models.CharField(max_length=16384)),
            ],
            options={
                'db_table': 'benefit_vc_benefit_trad_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BenefitVcDescrTradT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr_trad_value', models.CharField(max_length=16384)),
            ],
            options={
                'db_table': 'benefit_vc_descr_trad_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BenefitVcTitleTradT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_trad_value', models.CharField(max_length=16384)),
            ],
            options={
                'db_table': 'benefit_vc_title_trad_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('classid', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('end_time', models.CharField(blank=True, max_length=8, null=True)),
                ('start_time', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'calendar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DArtEStato',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=160, null=True)),
                ('definition', models.CharField(blank=True, max_length=1200, null=True)),
                ('alphacode', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'd_art_e_stato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DELang',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=160, null=True)),
                ('definition', models.CharField(blank=True, max_length=1200, null=True)),
                ('alphacode', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'd_e_lang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DEVc',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=160, null=True)),
                ('definition', models.CharField(blank=True, max_length=1200, null=True)),
                ('alphacode', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'd_e_vc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DMediaETipomm',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=160, null=True)),
                ('definition', models.CharField(blank=True, max_length=1200, null=True)),
                ('alphacode', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'd_media_e_tipomm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DRssEState',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=160, null=True)),
                ('definition', models.CharField(blank=True, max_length=1200, null=True)),
                ('alphacode', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'd_rss_e_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DTourETipoit',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=160, null=True)),
                ('definition', models.CharField(blank=True, max_length=1200, null=True)),
                ('alphacode', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'd_tour_e_tipoit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('classid', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('descr_it', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=200, null=True)),
                ('name_it', models.CharField(max_length=512)),
                ('notes', models.CharField(blank=True, max_length=1024, null=True)),
                ('open_time', models.CharField(blank=True, max_length=1024, null=True)),
                ('tickets', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('classid', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('name_it', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'event_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventCategoryNameTradT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_trad_value', models.CharField(max_length=16384)),
            ],
            options={
                'db_table': 'event_category_name_trad_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventDescrTradT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr_trad_value', models.TextField()),
            ],
            options={
                'db_table': 'event_descr_trad_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventNameTradT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_trad_value', models.CharField(max_length=16384)),
            ],
            options={
                'db_table': 'event_name_trad_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('classid', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'gallery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('classid', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('num', models.DecimalField(decimal_places=0, max_digits=15)),
                ('event', models.CharField(max_length=70)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('classid', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('name_it', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'media',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MediaNameTradT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_trad_value', models.CharField(blank=True, max_length=16384, null=True)),
            ],
            options={
                'db_table': 'media_name_trad_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('classid', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('descr', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('pubb_date', models.DateField()),
                ('title', models.CharField(max_length=256)),
                ('subtitle', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsDescrTradT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr_trad_value', models.CharField(max_length=16384)),
            ],
            options={
                'db_table': 'news_descr_trad_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsTitleTradT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_trad_value', models.CharField(max_length=16384)),
            ],
            options={
                'db_table': 'news_title_trad_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RetailerCategory',
            fields=[
                ('classid', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('name_it', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'retailer_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RetailerCategoryNameTradT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_trad_value', models.CharField(max_length=16384)),
            ],
            options={
                'db_table': 'retailer_category_name_trad_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RetailerVc',
            fields=[
                ('classid', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=2048)),
                ('name', models.CharField(max_length=1024)),
                ('geo', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'retailer_vc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rss',
            fields=[
                ('classid', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('pub_date', models.CharField(max_length=19)),
                ('text_it', models.TextField()),
                ('title_it', models.CharField(max_length=500)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('when_descr_it', models.TextField(blank=True, null=True)),
                ('when_is', models.TextField(blank=True, null=True)),
                ('where_is', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rss',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RssCategory',
            fields=[
                ('classid', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('category', models.TextField()),
            ],
            options={
                'db_table': 'rss_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RssTextTradT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_trad_value', models.CharField(max_length=16384)),
            ],
            options={
                'db_table': 'rss_text_trad_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RssTitleTradT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_trad_value', models.TextField()),
            ],
            options={
                'db_table': 'rss_title_trad_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RssWhenDescrTradT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_descr_trad_value', models.CharField(max_length=16384)),
            ],
            options={
                'db_table': 'rss_when_descr_trad_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RssWhenIs',
            fields=[
                ('classid', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('day', models.DateField()),
            ],
            options={
                'db_table': 'rss_when_is',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RssWhereIs',
            fields=[
                ('classid', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('location', models.TextField()),
            ],
            options={
                'db_table': 'rss_where_is',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpatialRefSys',
            fields=[
                ('srid', models.IntegerField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(blank=True, max_length=256, null=True)),
                ('auth_srid', models.IntegerField(blank=True, null=True)),
                ('srtext', models.CharField(blank=True, max_length=2048, null=True)),
                ('proj4text', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'spatial_ref_sys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('classid', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('descr_it', models.CharField(max_length=8192)),
                ('image_url', models.CharField(blank=True, max_length=100, null=True)),
                ('kml_path', models.CharField(blank=True, max_length=8192, null=True)),
                ('name_it', models.CharField(max_length=200)),
                ('geom_path', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('proximity_area', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TourDescrTradT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr_trad_value', models.CharField(max_length=16384)),
            ],
            options={
                'db_table': 'tour_descr_trad_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TourNameTradT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_trad_value', models.CharField(max_length=16384)),
            ],
            options={
                'db_table': 'tour_name_trad_t',
                'managed': False,
            },
        ),
    ]
