# Generated by Django 3.2.6 on 2021-09-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourismApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crowding',
            fields=[
                ('classid', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('date_creat', models.CharField(max_length=19)),
                ('val_real', models.FloatField()),
                ('val_stim', models.FloatField()),
                ('val_stor', models.FloatField()),
            ],
            options={
                'db_table': 'crowding',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogCrowd',
            fields=[
                ('classid', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('data_creat', models.CharField(max_length=19)),
                ('val_real', models.FloatField()),
                ('val_stim', models.FloatField()),
                ('val_stor', models.FloatField()),
            ],
            options={
                'db_table': 'log_crowd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogVc',
            fields=[
                ('classid', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('attivazione', models.DateField()),
                ('id_vc', models.CharField(max_length=40)),
                ('istante', models.CharField(max_length=19)),
                ('profilo', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'log_vc',
                'managed': False,
            },
        ),
    ]
