# Generated by Django 3.2.6 on 2021-10-24 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourismApp', '0003_lang'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lang',
        ),
    ]
