# Generated by Django 3.2.6 on 2021-11-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourismApp', '0004_delete_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtCapacity',
            fields=[
                ('classid', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('poi_cap', models.DecimalField(decimal_places=0, max_digits=15)),
                ('start_date', models.DateField()),
            ],
            options={
                'db_table': 'art_capacity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArtVisitingTime',
            fields=[
                ('classid', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('poi_visiting_time', models.DecimalField(decimal_places=0, max_digits=15)),
                ('start_date', models.DateField()),
            ],
            options={
                'db_table': 'art_visiting_time',
                'managed': False,
            },
        ),
    ]
